### ISSUE TITLE
Permanent session ID and a button to copy session ID 

### ISSUE THREAD

**Issue by JBraddockm** [steveseguin/live-chat-overlay#3]
Again, not sure if it is technically possible but with OBS Ninja, we are used to permanent session IDs. I was wondering if it is possible to generate a permanent session ID with an option to add YouTube video code i.e AdUw5RdyZxI to indicate that this is the chat we want to initialise the chat overlay. Something like: https://chat.overlay.ninja/?session=XXX&v=AdUw5RdyZxI

I can then send this link to the host and they can open it in Chrome as a normal webpage rather than a pop-up window.

The reason is that a remote host is going to control which comments appear on the live stream and if for some reason they close the chat, the session ID in my live stream setup will be invalid after they refresh the page.

Secondly, a link with a session ID is given when the YouTube Pop-out Chat is first opened. Is it possible to add a button to the UI to copy this link in case it is being dismissed mistakenly?

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/121645166-e060a280-ca61-11eb-9e1c-b0040ad5a1d8.png)

Added both a LINK button, and also in the plugin settings, there is an option to set the session ID. It will stay the same until manually changed now.

This change is not yet in the Chrome web store, but you can download the git repo and load the plugin manually. It should be in the store though within the next week, whenever it gets approved.
